image: node

#services:
#  postgres:latest

before_script:
  - mkdir -p ~/.ssh
  - (echo "$SSH_PRIVATE_KEY" | base64 -d) | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  - ssh-keyscan -H '178.170.47.43' >> ~/.ssh/known_hosts


deploy:
  stage: deploy
  environment:
    name: news.defispace.com
    url: news.defispace.com
  script:
    - bash deploy-scripts/deploy-script.sh
  only:
    - master
