# Generated by Django 5.1.dev20240109131842 on 2024-03-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_company_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='mark',
            field=models.BooleanField(default=False, null=True, verbose_name='Отображать на главной в Projects Scoring'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='pin',
            field=models.BooleanField(default=False, null=True, verbose_name='Отображать на главной в Editor Pick'),
        ),
    ]
