# Generated by Django 5.0.3 on 2024-03-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_company_mark_post_image_post_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='product_score_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='security_score_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='team_score_avg',
            field=models.FloatField(default=0),
        ),
    ]
