# Generated by Django 5.0.3 on 2024-04-07 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_company_product_score_avg_company_security_score_avg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='product_score_avg',
        ),
        migrations.RemoveField(
            model_name='company',
            name='security_score_avg',
        ),
        migrations.RemoveField(
            model_name='company',
            name='team_score_avg',
        ),
        migrations.AddField(
            model_name='post',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to='blog.company'),
        ),
        migrations.AddField(
            model_name='post',
            name='story',
            field=models.TextField(default=False),
        ),
    ]
