# Generated by Django 5.0.3 on 2024-04-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_company_product_score_avg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='story',
            field=models.TextField(default=''),
        ),
    ]
