# Generated by Django 5.0.3 on 2024-04-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='story',
            field=models.TextField(default=False),
        ),
    ]
