# Generated by Django 5.0.3 on 2024-04-21 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productscore',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_scores', to='blog.company'),
        ),
        migrations.AlterField(
            model_name='securityscore',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_scores', to='blog.company'),
        ),
        migrations.AlterField(
            model_name='teamscore',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_scores', to='blog.company'),
        ),
    ]
