# Generated by Django 5.0.3 on 2025-02-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_author_category_rename_comment_comment_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default='Anonymous User', max_length=255),
        ),
    ]
