# Generated by Django 5.0.3 on 2025-04-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_productscore_apy_1yr_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagrating',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
