# Generated by Django 5.0.3 on 2025-04-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_remove_company_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='published_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
