# Generated by Django 5.0.3 on 2025-04-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_company_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamscore',
            name='exposure_score',
            field=models.IntegerField(default=1),
        ),
    ]
