# Generated by Django 5.0.3 on 2025-04-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_teamscore_exposure_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
