# Generated by Django 5.0.3 on 2025-05-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_comment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
